
services:
  redis:
    image: redis:8.0
    ports:
      - '6379:6379'
    environment:
      REDIS_ARGS: --save 20 1
    deploy:
        replicas: 1
        restart_policy:
          condition: on-failure